import { AlgorithmConfig } from '../types/algorithm';
import { generateBubbleSort } from '../algorithms/sorting/bubbleSort';
import { generateSelectionSort } from '../algorithms/sorting/selectionSort';
import { generateInsertionSort } from '../algorithms/sorting/insertionSort';
import { generateMergeSort } from '../algorithms/sorting/mergeSort';
import { generateQuickSort } from '../algorithms/sorting/quickSort';
import { generateLinearSearch } from '../algorithms/searching/linearSearch';
import { generateBinarySearch } from '../algorithms/searching/binarySearch';
import { generateStackDemo } from '../algorithms/dataStructures/stack';
import { generateQueueDemo } from '../algorithms/dataStructures/queue';
import { generateLinkedListDemo } from '../algorithms/dataStructures/linkedList';
import { generateBSTInsert } from '../algorithms/trees/bstOperations';
import { generateInorderTraversal } from '../algorithms/trees/treeTraversals';

export const algorithmRegistry: Record<string, AlgorithmConfig> = {
  'bubble-sort': {
    slug: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Repeatedly compares adjacent elements and swaps them if they are in the wrong order.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [64, 34, 25, 12, 22, 11, 90],
    pseudocode: [
      'function bubbleSort(arr):',
      '  n = length(arr)',
      '  for i = 0 to n-1:',
      '    for j = 0 to n-i-2:',
      '      if arr[j] > arr[j+1]:',
      '        swap(arr[j], arr[j+1])',
      '    // Element at n-i-1 is sorted',
      '  if no swaps: break',
      '  return arr',
    ],
    generate: (input) => generateBubbleSort(input),
  },
  'selection-sort': {
    slug: 'selection-sort',
    name: 'Selection Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Finds the minimum element from unsorted part and puts it at the beginning.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [64, 25, 12, 22, 11],
    pseudocode: [
      'function selectionSort(arr):',
      '  n = length(arr)',
      '  for i = 0 to n-2:',
      '    minIdx = i',
      '    for j = i+1 to n-1:',
      '      if arr[j] < arr[minIdx]: minIdx = j',
      '    swap(arr[i], arr[minIdx])',
      '    // Position i is now sorted',
      '  return arr',
    ],
    generate: (input) => generateSelectionSort(input),
  },
  'insertion-sort': {
    slug: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Builds the sorted array one item at a time by inserting each element into its correct position.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [12, 11, 13, 5, 6],
    pseudocode: [
      'function insertionSort(arr):',
      '  // First element is already sorted',
      '  for i = 1 to n-1:',
      '    key = arr[i]',
      '    j = i - 1',
      '    while j >= 0 and arr[j] > key:',
      '      arr[j+1] = arr[j]; j--',
      '    arr[j+1] = key',
    ],
    generate: (input) => generateInsertionSort(input),
  },
  'merge-sort': {
    slug: 'merge-sort',
    name: 'Merge Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Divides the array into halves, sorts each half, and merges them back together.',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [38, 27, 43, 3, 9, 82, 10],
    pseudocode: [
      'function mergeSort(arr, start, end):',
      '  if start >= end: return',
      '  mid = (start + end) / 2',
      '  mergeSort(arr, start, mid)',
      '  mergeSort(arr, mid+1, end)',
      'function merge(start, mid, end):',
      '  left = arr[start..mid]',
      '  right = arr[mid+1..end]',
      '  while both have elements:',
      '    pick smaller, place in arr',
      '  copy remaining from left',
      '  copy remaining from right',
      '  // Merged section complete',
      '  return arr',
    ],
    generate: (input) => generateMergeSort(input),
  },
  'quick-sort': {
    slug: 'quick-sort',
    name: 'Quick Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Selects a pivot, partitions the array, and recursively sorts the sub-arrays.',
    timeComplexity: 'O(n log n) avg',
    spaceComplexity: 'O(log n)',
    difficulty: 'medium',
    defaultInput: [10, 7, 8, 9, 1, 5],
    pseudocode: [
      'function quickSort(arr, low, high):',
      '  if low < high:',
      '    pi = partition(arr, low, high)',
      '    quickSort(arr, low, pi-1)',
      'function partition(arr, low, high):',
      '  pivot = arr[high]',
      '  i = low - 1',
      '  for j = low to high-1:',
      '    if arr[j] < pivot:',
      '      i++; swap(arr[i], arr[j])',
      '  swap(arr[i+1], arr[high])',
      '  // Pivot at correct position',
      '  return i+1',
    ],
    generate: (input) => generateQuickSort(input),
  },
  'linear-search': {
    slug: 'linear-search',
    name: 'Linear Search',
    category: 'searching',
    visualizerType: 'array',
    description: 'Sequentially checks each element until the target is found or the list ends.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [10, 23, 45, 70, 11, 15],
    searchTarget: 70,
    pseudocode: [
      'function linearSearch(arr, target):',
      '  for i = 0 to n-1:',
      '    check arr[i]',
      '    if arr[i] == target:',
      '      return i  // Found!',
      '  return -1  // Not found',
    ],
    generate: (input, target) => generateLinearSearch(input, target ?? 70),
  },
  'binary-search': {
    slug: 'binary-search',
    name: 'Binary Search',
    category: 'searching',
    visualizerType: 'array',
    description: 'Efficiently searches a sorted array by repeatedly dividing the search interval in half.',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [2, 3, 4, 10, 40, 50, 70],
    searchTarget: 10,
    pseudocode: [
      'function binarySearch(arr, target):',
      '  low = 0, high = n-1',
      '  while low <= high:',
      '    mid = (low + high) / 2',
      '    if arr[mid] == target:',
      '      return mid  // Found!',
      '    else if arr[mid] < target:',
      '      low = mid + 1',
      '    else:',
      '      high = mid - 1',
      '  return -1  // Not found',
    ],
    generate: (input, target) => generateBinarySearch(input, target ?? 10),
  },
  'stack': {
    slug: 'stack',
    name: 'Stack',
    category: 'data-structures',
    visualizerType: 'stack-queue',
    description: 'LIFO data structure — last element added is the first to be removed.',
    timeComplexity: 'O(1) push/pop',
    spaceComplexity: 'O(n)',
    difficulty: 'easy',
    defaultInput: [10, 20, 30, 40],
    pseudocode: [
      'class Stack:',
      '  items = []',
      '  push(item):',
      '    items.append(item)',
      '  pop():',
      '    if empty: error',
      '    return items.removeLast()',
      '    // Removed from top',
      '  peek():',
      '    return items.last',
      '  // Demo complete',
    ],
    generate: () => generateStackDemo(),
  },
  'queue': {
    slug: 'queue',
    name: 'Queue',
    category: 'data-structures',
    visualizerType: 'stack-queue',
    description: 'FIFO data structure — first element added is the first to be removed.',
    timeComplexity: 'O(1) enqueue/dequeue',
    spaceComplexity: 'O(n)',
    difficulty: 'easy',
    defaultInput: [10, 20, 30, 40],
    pseudocode: [
      'class Queue:',
      '  items = []',
      '  enqueue(item):',
      '    items.append(item)',
      '  dequeue():',
      '    if empty: error',
      '    return items.removeFirst()',
      '    // Removed from front',
      '  front():',
      '    return items.first',
      '  // Demo complete',
    ],
    generate: () => generateQueueDemo(),
  },
  'linked-list': {
    slug: 'linked-list',
    name: 'Linked List',
    category: 'data-structures',
    visualizerType: 'linked-list',
    description: 'Linear data structure where elements are connected via pointers.',
    timeComplexity: 'O(n) search, O(1) insert at head',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [10, 20, 30, 40, 50],
    pseudocode: [
      'class LinkedList:',
      '  head = null',
      '  insertAtEnd(val):',
      '    create node, traverse to end, link',
      '  deleteNode(val):',
      '    find node, update prev.next',
      '    traverse to find node',
      '    about to delete',
      '    update pointers',
      '  traverse():',
      '    visit each node',
      '  // Demo complete',
    ],
    generate: () => generateLinkedListDemo(),
  },
  'bst-operations': {
    slug: 'bst-operations',
    name: 'BST Operations',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Insert values into a Binary Search Tree and visualize the tree structure.',
    timeComplexity: 'O(h)',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function insert(root, val):',
      '  if root is null: return new Node(val)',
      '  if val < root.val: go left',
      '  else: go right',
      '  return root',
      '  // BST complete',
    ],
    generate: (input) => generateBSTInsert(input),
  },
  'tree-traversals': {
    slug: 'tree-traversals',
    name: 'Tree Traversals',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Inorder, Preorder, and Postorder depth-first traversals of a BST.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function inorder(node):',
      '  if node is null: return',
      '  inorder(node.left)',
      '  visit(node)',
      '  inorder(node.right)',
      '  // Traversal complete',
    ],
    generate: (input) => generateInorderTraversal(input),
  },
};

export function getAlgorithmsByCategory(): Record<string, AlgorithmConfig[]> {
  const categories: Record<string, AlgorithmConfig[]> = {};
  Object.values(algorithmRegistry).forEach(algo => {
    if (!categories[algo.category]) {
      categories[algo.category] = [];
    }
    categories[algo.category].push(algo);
  });
  return categories;
}

export function getAlgorithm(slug: string): AlgorithmConfig | undefined {
  return algorithmRegistry[slug];
}
