import { AlgorithmConfig } from '../types/algorithm';
import { generateBubbleSort } from '../algorithms/sorting/bubbleSort';
import { generateSelectionSort } from '../algorithms/sorting/selectionSort';
import { generateInsertionSort } from '../algorithms/sorting/insertionSort';
import { generateMergeSort } from '../algorithms/sorting/mergeSort';
import { generateQuickSort } from '../algorithms/sorting/quickSort';
import { generateHeapSort } from '../algorithms/sorting/heapSort';
import { generateCountingSort } from '../algorithms/sorting/countingSort';
import { generateRadixSort } from '../algorithms/sorting/radixSort';
import { generateLinearSearch } from '../algorithms/searching/linearSearch';
import { generateBinarySearch } from '../algorithms/searching/binarySearch';
import { generateJumpSearch } from '../algorithms/searching/jumpSearch';
import { generateInterpolationSearch } from '../algorithms/searching/interpolationSearch';
import { generateStackDemo } from '../algorithms/dataStructures/stack';
import { generateQueueDemo } from '../algorithms/dataStructures/queue';
import { generateLinkedListDemo } from '../algorithms/dataStructures/linkedList';
import { generateDoublyLinkedListDemo } from '../algorithms/dataStructures/doublyLinkedList';
import { generateMinHeap } from '../algorithms/dataStructures/minHeap';
import { generateBSTInsert, generateBSTSearch, generateBSTDelete } from '../algorithms/trees/bstOperations';
import {
  generateInorderTraversal,
  generatePreorderTraversal,
  generatePostorderTraversal,
  generateLevelOrderTraversal,
} from '../algorithms/trees/treeTraversals';
import { generateGraphBFS } from '../algorithms/graphs/graphBFS';
import { generateGraphDFS } from '../algorithms/graphs/graphDFS';
import { generateFibonacciDP } from '../algorithms/dynamicProgramming/fibonacci';
import { generateLCS } from '../algorithms/dynamicProgramming/lcs';

export const algorithmRegistry: Record<string, AlgorithmConfig> = {
  'bubble-sort': {
    slug: 'bubble-sort',
    name: 'Bubble Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Repeatedly compares adjacent elements and swaps them if they are in the wrong order.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [64, 34, 25, 12, 22, 11, 90],
    pseudocode: [
      'function bubbleSort(arr):',
      '  n = length(arr)',
      '  for i = 0 to n-1:',
      '    for j = 0 to n-i-2:',
      '      if arr[j] > arr[j+1]:',
      '        swap(arr[j], arr[j+1])',
      '    // Element at n-i-1 is sorted',
      '  if no swaps: break',
      '  return arr',
    ],
    generate: (input) => generateBubbleSort(input),
  },
  'selection-sort': {
    slug: 'selection-sort',
    name: 'Selection Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Finds the minimum element from unsorted part and puts it at the beginning.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [64, 25, 12, 22, 11],
    pseudocode: [
      'function selectionSort(arr):',
      '  n = length(arr)',
      '  for i = 0 to n-2:',
      '    minIdx = i',
      '    for j = i+1 to n-1:',
      '      if arr[j] < arr[minIdx]: minIdx = j',
      '    swap(arr[i], arr[minIdx])',
      '    // Position i is now sorted',
      '  return arr',
    ],
    generate: (input) => generateSelectionSort(input),
  },
  'insertion-sort': {
    slug: 'insertion-sort',
    name: 'Insertion Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Builds the sorted array one item at a time by inserting each element into its correct position.',
    timeComplexity: 'O(n²)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [12, 11, 13, 5, 6],
    pseudocode: [
      'function insertionSort(arr):',
      '  // First element is already sorted',
      '  for i = 1 to n-1:',
      '    key = arr[i]',
      '    j = i - 1',
      '    while j >= 0 and arr[j] > key:',
      '      arr[j+1] = arr[j]; j--',
      '    arr[j+1] = key',
    ],
    generate: (input) => generateInsertionSort(input),
  },
  'merge-sort': {
    slug: 'merge-sort',
    name: 'Merge Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Divides the array into halves, sorts each half, and merges them back together.',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [38, 27, 43, 3, 9, 82, 10],
    pseudocode: [
      'function mergeSort(arr, start, end):',
      '  if start >= end: return',
      '  mid = (start + end) / 2',
      '  mergeSort(arr, start, mid)',
      '  mergeSort(arr, mid+1, end)',
      'function merge(start, mid, end):',
      '  left = arr[start..mid]',
      '  right = arr[mid+1..end]',
      '  while both have elements:',
      '    pick smaller, place in arr',
      '  copy remaining from left',
      '  copy remaining from right',
      '  // Merged section complete',
      '  return arr',
    ],
    generate: (input) => generateMergeSort(input),
  },
  'quick-sort': {
    slug: 'quick-sort',
    name: 'Quick Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Selects a pivot, partitions the array, and recursively sorts the sub-arrays.',
    timeComplexity: 'O(n log n) avg',
    spaceComplexity: 'O(log n)',
    difficulty: 'medium',
    defaultInput: [10, 7, 8, 9, 1, 5],
    pseudocode: [
      'function quickSort(arr, low, high):',
      '  if low < high:',
      '    pi = partition(arr, low, high)',
      '    quickSort(arr, low, pi-1)',
      'function partition(arr, low, high):',
      '  pivot = arr[high]',
      '  i = low - 1',
      '  for j = low to high-1:',
      '    if arr[j] < pivot:',
      '      i++; swap(arr[i], arr[j])',
      '  swap(arr[i+1], arr[high])',
      '  // Pivot at correct position',
      '  return i+1',
    ],
    generate: (input) => generateQuickSort(input),
  },
  'heap-sort': {
    slug: 'heap-sort',
    name: 'Heap Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Builds a max-heap then repeatedly extracts the largest element to the end of the array.',
    timeComplexity: 'O(n log n)',
    spaceComplexity: 'O(1)',
    difficulty: 'medium',
    defaultInput: [12, 11, 13, 5, 6, 7],
    pseudocode: [
      'function heapSort(arr):',
      '  n = length(arr)',
      '  // Phase 1: build max-heap',
      '  for i = n/2 - 1 down to 0:',
      '    heapify(arr, n, i)',
      '    // compare with left child',
      '    // swap if child larger',
      '  // Phase 2: extract max repeatedly',
      '  for i = n-1 down to 1:',
      '    swap(arr[0], arr[i]); heapify(arr, i, 0)',
      '  return arr',
    ],
    generate: (input) => generateHeapSort(input),
  },
  'counting-sort': {
    slug: 'counting-sort',
    name: 'Counting Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Non-comparison sort that counts occurrences of each key, then computes positions from a cumulative count.',
    timeComplexity: 'O(n + k)',
    spaceComplexity: 'O(n + k)',
    difficulty: 'medium',
    defaultInput: [4, 2, 2, 8, 3, 3, 1],
    pseudocode: [
      'function countingSort(arr):',
      '  find min and max → range k',
      '  count = array of size k filled with 0',
      '  for x in arr: count[x - min]++',
      '  // cumulative count',
      '  for i = 1 to k-1: count[i] += count[i-1]',
      '  // place elements right-to-left for stability',
      '  for i = n-1 down to 0: place arr[i] at output[count[arr[i]-min]-1]',
      '  return output',
    ],
    generate: (input) => generateCountingSort(input),
  },
  'radix-sort': {
    slug: 'radix-sort',
    name: 'Radix Sort',
    category: 'sorting',
    visualizerType: 'array',
    description: 'Sorts integers digit by digit (least significant first) using counting sort as a stable subroutine.',
    timeComplexity: 'O(d · (n + k))',
    spaceComplexity: 'O(n + k)',
    difficulty: 'medium',
    defaultInput: [170, 45, 75, 90, 802, 24, 2, 66],
    pseudocode: [
      'function radixSort(arr):',
      '  find max value → determines number of digits d',
      '  exp = 1',
      '  for each digit position (1, 10, 100, ...):',
      '    // count occurrences of each digit 0-9',
      '    // build cumulative count',
      '    // place into output stably by current digit',
      '    copy output back into arr',
      '  return arr',
    ],
    generate: (input) => generateRadixSort(input),
  },
  'linear-search': {
    slug: 'linear-search',
    name: 'Linear Search',
    category: 'searching',
    visualizerType: 'array',
    description: 'Sequentially checks each element until the target is found or the list ends.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [10, 23, 45, 70, 11, 15],
    searchTarget: 70,
    pseudocode: [
      'function linearSearch(arr, target):',
      '  for i = 0 to n-1:',
      '    check arr[i]',
      '    if arr[i] == target:',
      '      return i  // Found!',
      '  return -1  // Not found',
    ],
    generate: (input, target) => generateLinearSearch(input, target ?? 70),
  },
  'binary-search': {
    slug: 'binary-search',
    name: 'Binary Search',
    category: 'searching',
    visualizerType: 'array',
    description: 'Efficiently searches a sorted array by repeatedly dividing the search interval in half.',
    timeComplexity: 'O(log n)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [2, 3, 4, 10, 40, 50, 70],
    searchTarget: 10,
    pseudocode: [
      'function binarySearch(arr, target):',
      '  low = 0, high = n-1',
      '  while low <= high:',
      '    mid = (low + high) / 2',
      '    if arr[mid] == target:',
      '      return mid  // Found!',
      '    else if arr[mid] < target:',
      '      low = mid + 1',
      '    else:',
      '      high = mid - 1',
      '  return -1  // Not found',
    ],
    generate: (input, target) => generateBinarySearch(input, target ?? 10),
  },
  'jump-search': {
    slug: 'jump-search',
    name: 'Jump Search',
    category: 'searching',
    visualizerType: 'array',
    description: 'Jumps ahead by fixed √n strides on a sorted array, then linearly scans the final block.',
    timeComplexity: 'O(√n)',
    spaceComplexity: 'O(1)',
    difficulty: 'medium',
    defaultInput: [0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144],
    searchTarget: 55,
    pseudocode: [
      'function jumpSearch(arr, target):',
      '  step = floor(sqrt(n)); prev = 0',
      '  // Phase 1: jump until block end ≥ target',
      '  while arr[curr] < target: prev = curr+1; curr += step',
      '  // Phase 2: linear scan within block',
      '  for i = prev to min(curr, n-1):',
      '    compare arr[i] with target',
      '    if arr[i] == target: return i',
      '    if arr[i] > target: break',
      '  // not found in expected block',
      '  return -1',
    ],
    generate: (input, target) => generateJumpSearch(input, target ?? 55),
  },
  'interpolation-search': {
    slug: 'interpolation-search',
    name: 'Interpolation Search',
    category: 'searching',
    visualizerType: 'array',
    description: 'Probes a sorted, uniformly distributed array at a position estimated by linear interpolation.',
    timeComplexity: 'O(log log n) avg, O(n) worst',
    spaceComplexity: 'O(1)',
    difficulty: 'medium',
    defaultInput: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    searchTarget: 70,
    pseudocode: [
      'function interpolationSearch(arr, target):',
      '  low = 0; high = n-1',
      '  while low ≤ high and arr[low] ≤ target ≤ arr[high]:',
      '    pos = low + ((target - arr[low]) × (high-low)) / (arr[high] - arr[low])',
      '    if arr[pos] == target:',
      '      return pos',
      '    else if arr[pos] < target:',
      '      low = pos + 1',
      '    else:',
      '      high = pos - 1',
      '  return -1',
    ],
    generate: (input, target) => generateInterpolationSearch(input, target ?? 70),
  },
  'stack': {
    slug: 'stack',
    name: 'Stack',
    category: 'data-structures',
    visualizerType: 'stack-queue',
    description: 'LIFO data structure — last element added is the first to be removed.',
    timeComplexity: 'O(1) push/pop',
    spaceComplexity: 'O(n)',
    difficulty: 'easy',
    defaultInput: [10, 20, 30, 40],
    pseudocode: [
      'class Stack:',
      '  items = []',
      '  push(item):',
      '    items.append(item)',
      '  pop():',
      '    if empty: error',
      '    return items.removeLast()',
      '    // Removed from top',
      '  peek():',
      '    return items.last',
      '  // Demo complete',
    ],
    generate: () => generateStackDemo(),
  },
  'queue': {
    slug: 'queue',
    name: 'Queue',
    category: 'data-structures',
    visualizerType: 'stack-queue',
    description: 'FIFO data structure — first element added is the first to be removed.',
    timeComplexity: 'O(1) enqueue/dequeue',
    spaceComplexity: 'O(n)',
    difficulty: 'easy',
    defaultInput: [10, 20, 30, 40],
    pseudocode: [
      'class Queue:',
      '  items = []',
      '  enqueue(item):',
      '    items.append(item)',
      '  dequeue():',
      '    if empty: error',
      '    return items.removeFirst()',
      '    // Removed from front',
      '  front():',
      '    return items.first',
      '  // Demo complete',
    ],
    generate: () => generateQueueDemo(),
  },
  'linked-list': {
    slug: 'linked-list',
    name: 'Linked List',
    category: 'data-structures',
    visualizerType: 'linked-list',
    description: 'Linear data structure where elements are connected via pointers.',
    timeComplexity: 'O(n) search, O(1) insert at head',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [10, 20, 30, 40, 50],
    pseudocode: [
      'class LinkedList:',
      '  head = null',
      '  insertAtEnd(val):',
      '    create node, traverse to end, link',
      '  deleteNode(val):',
      '    find node, update prev.next',
      '    traverse to find node',
      '    about to delete',
      '    update pointers',
      '  traverse():',
      '    visit each node',
      '  // Demo complete',
    ],
    generate: () => generateLinkedListDemo(),
  },
  'doubly-linked-list': {
    slug: 'doubly-linked-list',
    name: 'Doubly Linked List',
    category: 'data-structures',
    visualizerType: 'linked-list',
    description: 'Each node carries pointers to both its next and previous neighbors, enabling O(1) deletion when the node is known and traversal in both directions.',
    timeComplexity: 'O(n) search, O(1) insert/delete at known node',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [10, 20, 30, 40, 50],
    pseudocode: [
      'class DoublyLinkedList:',
      '  head = null, tail = null',
      '  insertAtHead(val):',
      '    new.prev = null; new.next = head; head.prev = new; head = new',
      '  insertAtTail(val):',
      '    new.prev = tail; tail.next = new; tail = new',
      '  insertAtPosition(val, pos):',
      '    walk forward pos steps',
      '    splice new between prev and curr; rewire both prev/next',
      '  delete(val):',
      '    find node by walking forward',
      '    node.prev.next = node.next; node.next.prev = node.prev',
      '    detached node freed',
      '  traverseForward():  walk via .next',
      '  traverseBackward(): walk via .prev',
      '  // Demo complete',
    ],
    generate: () => generateDoublyLinkedListDemo(),
  },
  'min-heap': {
    slug: 'min-heap',
    name: 'Min-Heap / Priority Queue',
    category: 'data-structures',
    visualizerType: 'heap',
    description: 'Array-backed complete binary tree where every parent is ≤ its children. Foundation of priority queues and heap-based sorting.',
    timeComplexity: 'O(log n) insert/extract, O(n) build-heap',
    spaceComplexity: 'O(1) extra',
    difficulty: 'medium',
    defaultInput: [9, 4, 7, 1, 8, 3, 5],
    pseudocode: [
      'class MinHeap:',
      '  heap = []  // index i → children at 2i+1, 2i+2',
      '  buildHeap(arr):',
      '    for i = n/2 - 1 down to 0:',
      '      siftDown(i)',
      '      // compare with left child',
      '      // compare with right child',
      '      // swap if smallest child < parent',
      '  // build complete — heap[0] is the minimum',
      '  insert(val):',
      '    append val, then siftUp from last index',
      '    while parent > current: swap up',
      '  // insertion settled',
      '  extractMin():',
      '    swap heap[0] with last, pop, siftDown(0)',
      '  // Demo complete',
    ],
    generate: (input) => generateMinHeap(input),
  },
  'bst-operations': {
    slug: 'bst-operations',
    name: 'BST Operations',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Insert values into a Binary Search Tree and visualize the tree structure.',
    timeComplexity: 'O(h)',
    spaceComplexity: 'O(n)',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function insert(root, val):',
      '  if root is null: return new Node(val)',
      '  if val < root.val: go left',
      '  else: go right',
      '  return root',
      '  // BST complete',
    ],
    generate: (input) => generateBSTInsert(input),
  },
  'bst-search': {
    slug: 'bst-search',
    name: 'BST Search',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Searches a Binary Search Tree by walking left for smaller targets and right for larger.',
    timeComplexity: 'O(h)',
    spaceComplexity: 'O(1)',
    difficulty: 'easy',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    searchTarget: 40,
    pseudocode: [
      'function search(root, target):',
      '  while root is not null:',
      '    if target == root.val:',
      '      return root  // found',
      '    if target < root.val:',
      '      root = root.left',
      '    else:',
      '      root = root.right',
      '  // walked off the tree',
      '  return null',
    ],
    generate: (input, target) => generateBSTSearch(input, target ?? 40),
  },
  'bst-delete': {
    slug: 'bst-delete',
    name: 'BST Delete',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Removes a node from a BST handling three cases: leaf, one child, and two children (in-order successor).',
    timeComplexity: 'O(h)',
    spaceComplexity: 'O(h)',
    difficulty: 'hard',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    searchTarget: 30,
    pseudocode: [
      'function delete(root, val):',
      '  if root is null: return null',
      '  if val != root.val: recurse left or right',
      '  else:  // found node to delete',
      '    found target',
      '    Case 1: leaf → return null',
      '    Case 2: one child → return that child',
      '    Case 3: two children → find in-order successor',
      '      copy successor value, recursively delete successor',
      '  return root',
      '  // value not in tree',
      '  // BST property restored',
    ],
    generate: (input, target) => generateBSTDelete(input, target ?? 30),
  },
  'inorder-traversal': {
    slug: 'inorder-traversal',
    name: 'Inorder Traversal',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Depth-first traversal in Left → Root → Right order. Yields sorted output for a BST.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function inorder(node):',
      '  if node is null: return',
      '  inorder(node.left)',
      '  visit(node)',
      '  inorder(node.right)',
      '  // Traversal complete',
    ],
    generate: (input) => generateInorderTraversal(input),
  },
  'preorder-traversal': {
    slug: 'preorder-traversal',
    name: 'Preorder Traversal',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Depth-first traversal in Root → Left → Right order. Useful for cloning or serializing a tree.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function preorder(node):',
      '  if node is null: return',
      '  visit(node)',
      '  preorder(node.left)',
      '  preorder(node.right)',
      '  // Traversal complete',
    ],
    generate: (input) => generatePreorderTraversal(input),
  },
  'postorder-traversal': {
    slug: 'postorder-traversal',
    name: 'Postorder Traversal',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Depth-first traversal in Left → Right → Root order. Useful for safely deleting a tree or evaluating expression trees.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(h)',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function postorder(node):',
      '  if node is null: return',
      '  postorder(node.left)',
      '  postorder(node.right)',
      '  visit(node)',
      '  // process node after subtrees',
      '  // Traversal complete',
    ],
    generate: (input) => generatePostorderTraversal(input),
  },
  'level-order-traversal': {
    slug: 'level-order-traversal',
    name: 'Level-Order Traversal',
    category: 'trees',
    visualizerType: 'tree',
    description: 'Breadth-first traversal — visits nodes level by level, left to right, using a queue.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(w) where w = max width',
    difficulty: 'medium',
    defaultInput: [50, 30, 70, 20, 40, 60, 80],
    pseudocode: [
      'function levelOrder(root):',
      '  if root is null: return',
      '  queue = [root]',
      '  while queue is not empty:',
      '    node = queue.dequeue(); visit(node)',
      '    if node.left:  queue.enqueue(node.left)',
      '    if node.right: queue.enqueue(node.right)',
      '  // Traversal complete',
    ],
    generate: (input) => generateLevelOrderTraversal(input),
  },
  'graph-bfs': {
    slug: 'graph-bfs',
    name: 'Graph BFS',
    category: 'graphs',
    visualizerType: 'graph',
    description: 'Breadth-first search explores a graph level by level using a FIFO queue, discovering all nodes at distance k before any at distance k+1.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V)',
    difficulty: 'medium',
    defaultInput: [],
    pseudocode: [
      'function bfs(graph, source):',
      '  visited = {}; dist[source] = 0',
      '  queue = [source]',
      '  while queue not empty:',
      '    u = queue.dequeue()',
      '    for each neighbor v of u:',
      '      if v not visited:',
      '        dist[v] = dist[u] + 1; queue.enqueue(v)',
      '      // else: already discovered, skip',
      '    // u fully processed',
    ],
    generate: () => generateGraphBFS(),
  },
  'graph-dfs': {
    slug: 'graph-dfs',
    name: 'Graph DFS',
    category: 'graphs',
    visualizerType: 'graph',
    description: 'Depth-first search dives along each branch as deep as possible before backtracking, naturally implemented with recursion or an explicit stack.',
    timeComplexity: 'O(V + E)',
    spaceComplexity: 'O(V) recursion stack',
    difficulty: 'medium',
    defaultInput: [],
    pseudocode: [
      'function dfs(graph, source):',
      '  visited = {}',
      '  recurse(u, parent):',
      '    mark u as visiting',
      '    for each neighbor v of u (skip parent):',
      '      if v not visited:',
      '        recurse(v, u)  // tree edge',
      '      else:',
      '        // back edge — skip',
      '    mark u as fully visited',
      '  recurse(source, null)',
    ],
    generate: () => generateGraphDFS(),
  },
  'fibonacci-dp': {
    slug: 'fibonacci-dp',
    name: 'Fibonacci (DP)',
    category: 'dynamic-programming',
    visualizerType: 'dp-table',
    description: 'Bottom-up dynamic programming computes Fibonacci in O(n) by filling a 1-D table where dp[i] = dp[i-1] + dp[i-2], eliminating the exponential redundancy of naive recursion.',
    timeComplexity: 'O(n)',
    spaceComplexity: 'O(n) — O(1) with rolling variables',
    difficulty: 'easy',
    defaultInput: [8],
    pseudocode: [
      'function fib(n):',
      '  dp[0] = 0',
      '  dp[1] = 1',
      '  for i = 2 to n:',
      '    read dp[i-1] and dp[i-2]',
      '    dp[i] = dp[i-1] + dp[i-2]',
      '  return dp[n]',
      '  // dp table fully filled',
    ],
    generate: (input) => generateFibonacciDP(input),
  },
  'lcs': {
    slug: 'lcs',
    name: 'Longest Common Subsequence',
    category: 'dynamic-programming',
    visualizerType: 'dp-table',
    description: 'Finds the longest subsequence common to two strings using a 2-D DP table — diagonal step on character match, max of up/left on mismatch — then traces the table back to reconstruct the subsequence.',
    timeComplexity: 'O(m·n)',
    spaceComplexity: 'O(m·n) — O(min(m,n)) with row compression',
    difficulty: 'medium',
    defaultInput: [],
    pseudocode: [
      'function lcs(A, B):',
      '  dp[0][*] = 0   // empty prefix of B',
      '  dp[*][0] = 0   // empty prefix of A',
      '  for i = 1 to |B|:',
      '    for j = 1 to |A|:',
      '      if B[i-1] == A[j-1]:',
      '        dp[i][j] = dp[i-1][j-1] + 1',
      '      else:',
      '        read dp[i-1][j] and dp[i][j-1]',
      '        dp[i][j] = max(dp[i-1][j], dp[i][j-1])',
      '  // dp[|B|][|A|] = LCS length',
      '  traceback at match: emit char, move diagonally',
      '  traceback on mismatch: move up if dp[i-1][j] ≥ dp[i][j-1]',
      '  otherwise: move left',
      '  // reverse collected chars → LCS string',
    ],
    generate: () => generateLCS(),
  },
};

export function getAlgorithmsByCategory(): Record<string, AlgorithmConfig[]> {
  const categories: Record<string, AlgorithmConfig[]> = {};
  Object.values(algorithmRegistry).forEach(algo => {
    if (!categories[algo.category]) {
      categories[algo.category] = [];
    }
    categories[algo.category].push(algo);
  });
  return categories;
}

export function getAlgorithm(slug: string): AlgorithmConfig | undefined {
  return algorithmRegistry[slug];
}

export function getAlgorithmNavigation(slug: string) {
  const allSlugs = Object.keys(algorithmRegistry);
  const idx = allSlugs.indexOf(slug);
  const config = algorithmRegistry[slug];
  if (!config || idx === -1) return null;

  const catAlgos = Object.values(algorithmRegistry).filter(a => a.category === config.category);
  const posInCat = catAlgos.findIndex(a => a.slug === slug) + 1;

  return {
    prev: idx > 0 ? algorithmRegistry[allSlugs[idx - 1]] : null,
    next: idx < allSlugs.length - 1 ? algorithmRegistry[allSlugs[idx + 1]] : null,
    categoryPosition: posInCat,
    categoryTotal: catAlgos.length,
  };
}
